Set-Location C:\saas\emailabtesttracker

@'
# NextAuth
NEXTAUTH_SECRET=replace-with-a-random-secret
NEXTAUTH_URL=http://localhost:3000

# App URL
NEXT_PUBLIC_APP_URL=http://localhost:3000

# Firebase (Client - from Firebase Console web app config)
NEXT_PUBLIC_FIREBASE_API_KEY=...
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=...
NEXT_PUBLIC_FIREBASE_PROJECT_ID=...
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=...
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=...
NEXT_PUBLIC_FIREBASE_APP_ID=...
NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=...

# Firebase (Admin - from Service Account JSON)
FIREBASE_PROJECT_ID=...
FIREBASE_CLIENT_EMAIL=...
FIREBASE_PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n"

# Google OAuth (optional)
# GOOGLE_CLIENT_ID=...
# GOOGLE_CLIENT_SECRET=...

# Stripe (optional; only needed if you use billing routes/pages)
# STRIPE_SECRET_KEY=sk_test_...
# STRIPE_WEBHOOK_SECRET=whsec_...
# STRIPE_PRICE_ID_SOLO=price_...
# STRIPE_PRICE_ID_AGENCY=price_...
# STRIPE_PRICE_ID_PRO=price_...
'@ | Out-File -FilePath .\.env.local -Encoding utf8